# Generated by Django 3.0.7 on 2020-11-05 09:19

from django.db import migrations, models
import rad.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', sorl.thumbnail.fields.ImageField(upload_to=rad.utils.images_directory_path)),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
