# Generated by Django 3.0.7 on 2020-11-05 09:19

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_back', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_discounted', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trousercategory', to='menu.Menu')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrouserVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9)),
                ('trouser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='shop.Trouser')),
            ],
        ),
        migrations.CreateModel(
            name='TrouserMETA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('30', '30W'), ('32', '32W'), ('34', '34W'), ('36', '36W'), ('38', '38W'), ('40', '40W'), ('42', '42W')], max_length=2)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('trouser_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trouser_variant_meta', to='shop.TrouserVariant')),
            ],
            options={
                'ordering': ['size'],
            },
        ),
    ]
